using System;

namespace PWAFeaturesRnd.Models.Report.Finance
{
    public class RunningCostRecalReportHeaderDetails
    {
        /// <summary>
        /// Gets or sets the name of the vessel.
        /// </summary>
        /// <value>
        /// The name of the vessel.
        /// </value>
        public string VesselName { get; set; }

        /// <summary>
        /// Gets or sets from date time.
        /// </summary>
        /// <value>
        /// From date time.
        /// </value>
        public DateTime FromDateTime { get; set; }

        /// <summary>
        /// Gets or sets to date time.
        /// </summary>
        /// <value>
        /// To date time.
        /// </value>
        public DateTime ToDateTime { get; set; }

        /// <summary>
        /// Gets or sets the number of days.
        /// </summary>
        /// <value>
        /// The number of days.
        /// </value>
        public int NumberOfDays { get; set; }

        /// <summary>
        /// Gets or sets the name of the company.
        /// </summary>
        /// <value>
        /// The name of the company.
        /// </value>
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or sets the coy identifier.
        /// </summary>
        /// <value>
        /// The coy identifier.
        /// </value>
        public string CoyId { get; set; }

        /// <summary>
        /// Gets or sets the currency.
        /// </summary>
        /// <value>
        /// The currency.
        /// </value>
        public string Currency { get; set; }

        /// <summary>
        /// Gets or sets the generated by.
        /// </summary>
        /// <value>
        /// The generated by.
        /// </value>
        public string GeneratedBy { get; set; }

        /// <summary>
        /// Gets or sets the generated on.
        /// </summary>
        /// <value>
        /// The generated on.
        /// </value>
        public DateTime? GeneratedOn { get; set; }

        /// <summary>
        /// Gets or sets the rc from date time.
        /// </summary>
        /// <value>
        /// The rc from date time.
        /// </value>
        public DateTime RCFromDateTime { get; set; }

        /// <summary>
        /// Gets or sets the rc to date time.
        /// </summary>
        /// <value>
        /// The rc to date time.
        /// </value>
        public DateTime RCToDateTime { get; set; }
    }
}
